/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdIN1;
 extern const CStringDictionary::TStringId g_nStringIdIN2;
 extern const CStringDictionary::TStringId g_nStringIdIN3;
 extern const CStringDictionary::TStringId g_nStringIdIN4;
 extern const CStringDictionary::TStringId g_nStringIdIN5;
 extern const CStringDictionary::TStringId g_nStringIdIN6;
 extern const CStringDictionary::TStringId g_nStringIdIN7;
 extern const CStringDictionary::TStringId g_nStringIdIN8;
 extern const CStringDictionary::TStringId g_nStringIdIND;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdINITO;
 extern const CStringDictionary::TStringId g_nStringIdOUT1;
 extern const CStringDictionary::TStringId g_nStringIdOUT2;
 extern const CStringDictionary::TStringId g_nStringIdOUT3;
 extern const CStringDictionary::TStringId g_nStringIdOUT4;
 extern const CStringDictionary::TStringId g_nStringIdOUT5;
 extern const CStringDictionary::TStringId g_nStringIdOUT6;
 extern const CStringDictionary::TStringId g_nStringIdOUT7;
 extern const CStringDictionary::TStringId g_nStringIdOUT8;
 extern const CStringDictionary::TStringId g_nStringIdPLC01A1;
 extern const CStringDictionary::TStringId g_nStringIdQI;
 extern const CStringDictionary::TStringId g_nStringIdQO;
 extern const CStringDictionary::TStringId g_nStringIdSTATUS;
 extern const CStringDictionary::TStringId g_nStringIdUINT;
 extern const CStringDictionary::TStringId g_nStringIdUpdateInterval;
 extern const CStringDictionary::TStringId g_nStringIdWSTRING;

